# Site settings
title: Deep Learning Notes
email: arunpatala@gmail.com
description: "personal notes on topics in deep learning"
baseurl: "" # the subpath of your site, e.g., "/blog"
url: "https://arunpatala.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM

